#!/bin/sh
# Contains at least UPSIDE_TIER
source /etc/upside/service/base
service_name=$1
service_version=$2
service_base_path=/etc/upside/service/$service_name/$UPSIDE_TIER/$service_version
service_environment=$service_base_path/environment
if [ -e $service_environment ]
then
  source $service_environment
fi
exec /opt/$service_name/bin/$service_name server $service_base_path/app.yml

